services:
  stats-server:
    build: ./stats-server/service
    image: stats-server
    container_name: "stats-server-container"
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:14-alpine
    container_name: "stats-db-container"
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ./ewm-service/
    image: ewm-service
    container_name: "ewm-service-container"
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-service
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - STATS_SERVICE_URL=http://stats-server:9090/

  ewm-db:
    image: postgres:14-alpine
    container_name: "ewm-service-db-container"
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-service
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password